from misclases import Libretas, zapatos, libro
print("Caracteristicas de libretas: ")
Libretas = Libretas(100, "resorte")
Libretas.imprimirinfo()
print("Caracteristicas de zapatos: ")
 zapatos= zapatos(23 , "negros")
zapatos.imprimirinfo()
print("Datos de la libro: ")
libro = libro("Grande", "Programacion" )
libro.imprimirinfo()
